---
title: "FinalProject"
author: "Eeman, Linda, Sofia"
date: "2025-11-06"
output:
  pdf_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)

dat <- read_csv("cancer patient data sets 2.csv")

library(MASS)

dat <- read_csv("cancer patient data sets 2.csv")

names(dat) <- make.names(names(dat))

names(dat)

dat$Level <- factor(dat$Level,
                     levels = c("Low","Medium","High"),
                     ordered = TRUE)

dat <- dat |>
  mutate(High = if_else(Level == "High", 1, 0))



m1causes <- glm(High ~ Gender + Genetic.Risk + Age + Smoking + Air.Pollution + Obesity, data = dat, family = "binomial")

m1symptoms <- glm(High ~  Chest.Pain + Coughing.of.Blood + Shortness.of.Breath + Weight.Loss + Frequent.Cold, data = dat, family = "binomial")

summary(m1causes)
summary(m1symptoms)

exp(7.6069)
exp(4.1667)
exp(6.3718)
exp(-0.7692)
exp( 10.4882)
```

```{r, echo=FALSE}
library(gt)


df <- data.frame(
  Estimate = c(-16.270, 1.928, -0.258,-0.052,.794,1.227,1.590),
  "Standard Error" = c(1.796, 0.476, 0.142,0.014,0.102,.137,.149),
  pValue = c(2.00e-16,5.14e-5,0.071,2.00e-4,1.15e-14,2.00e-16,2.00e-16),
  row.names = c("Intercept","Gender", "Genetic Risk", "Age","Smoking","Air Pollution", "Obesity")
)
df %>%
  gt(rownames_to_stub = TRUE) %>%
  tab_header(
    title = "Logression Coefficients For Cancer Markers"
  )



dg <- data.frame(
  Estimate = c(-18.285,0.848,1.356,-0.147,1.102,0.368),
  "Standard Error" = c(1.762,0.148,0.147,0.112,0.176,0.104),
  pValue = c(2e-16,1.14e-8,2e-16,0.190,3.42e-10,3.89e-4),
  row.names = c("Intercept","Chest Pain","Coughing of Blood","Shortness of Breath","Weight Loss","Frequent Cold")
)
dg %>%
  gt(rownames_to_stub = TRUE) %>%
  tab_header(
    title = "Logression Coefficients For Cancer Symptoms"
  )
```

```{r,include=FALSE}
library(tidyverse)
data <- read_csv("cancer patient data sets 2.csv")

m2 <- glm(High ~ Gender + Genetic.Risk + Age + Smoking + Air.Pollution + Obesity, data = dat, family = "binomial")

summary(m2)
```



```{r,echo=FALSE}
library(ggplot2)
ggplot(dat, aes(x = Level, y = `Air.Pollution`)) +
  geom_bar(stat = "identity")
ggplot(dat, aes(x = Level, y = `Genetic.Risk`)) +
  geom_bar(stat = "identity")
ggplot(dat, aes(x = Level, y = `Smoking`)) +
  geom_bar(stat = "identity")

table(dat$"Genetic.Risk", dat$Level)
chisq.test(table(dat$"Genetic.Risk", dat$Level)) 

```

```{r,echo=FALSE}
library(tidyverse)

dat_long <- dat|>
  pivot_longer(
    cols = c(`Air.Pollution`, `Genetic.Risk`, Smoking),
    names_to = "Variable",
    values_to = "Value")


ggplot(dat_long, aes(x = Level, y = Value, fill = Level)) +
  geom_boxplot() +
  facet_wrap(~ Variable, scales = "free_y") +
  theme_bw()
```


```{r,include=FALSE}
library(tidyverse)

dat <- read_csv("cancer patient data sets 2.csv")

library(tidyverse)
library(MASS)

data <- read_csv("cancer patient data sets 2.csv")

names(data) <- make.names(names(data))

names(data)

data$Level <- factor(data$Level,
                     levels = c("Low","Medium","High"),
                     ordered = TRUE)

m1 <- lm(Level ~ Age + Gender + Air.Pollution + Alcohol.use + Dust.Allergy + OccuPational.Hazards + Genetic.Risk + chronic.Lung.Disease + Balanced.Diet + Obesity + Smoking + Passive.Smoker + Chest.Pain + Coughing.of.Blood + Fatigue + Weight.Loss + Shortness.of.Breath + Wheezing + Swallowing.Difficulty + Clubbing.of.Finger.Nails + Frequent.Cold + Dry.Cough + Snoring, data = data)


print(m1)


```

